### ISSUE TITLE
The road surface images!!!

### ISSUE THREAD

**Issue by tientuyen-k59** [ZhengPeng7/detect_visual_limits#1]

**Comment by tientuyen-k59** [comment]
I have a question. Which is the algorithm to generate the road surface images?

**Comment by ZhengPeng7** [comment]
> I have a question. Which is the algorithm to generate the road surface images?

I'm sorry, in my task, all the surveillance images are all in only six traffic scenes. So I used a semi-auto and dull process to extract the six road areas from images without too much fog.

**Comment by tientuyen07** [comment]
> > I have a question. Which is the algorithm to generate the road surface images?
> 
> I'm sorry, in my task, all the surveillance images are all in only six traffic scenes. So I used a semi-auto and dull process to extract the six road areas from images without too much fog.

Yes, thank you for your answer.

**Comment by tientuyen07** [comment]
> > I have a question. Which is the algorithm to generate the road surface images?
> 
> I'm sorry, in my task, all the surveillance images are all in only six traffic scenes. So I used a semi-auto and dull process to extract the six road areas from images without too much fog.

Yes, thank you for your answer.
